### PR TITLE
Simplify script and fix escaping

### PR DESCRIPTION
**Pull request by zmeyc**
- Use jq's built-in env and filtering
- Use jq's compact mode instead of dropping all spaces and endlines
- Escape \ instead of /

### CODE REVIEW

**Comment by axelhzf** [comment]
Hi, thank you for taking the time to improve the script.

I am getting the following error

```
docker build --tag cra-docker-env .
docker run \
    -e REACT_APP_API='http://api.com' \
    -e REACT_APP_TOKEN='123' \
    -p8080:80 \
    cra-docker-env

/docker-entrypoint.sh: line 6: ESCAPED_ENV_JSON: parameter not set
```

**Comment by zmeyc** [comment]
@axelhzf Sorry, I fixed this, will send updated version soon. Trying to fix escaping.

**Comment by zmeyc** [comment]
@axelhzf I repushed a fixed version with improved sed replacement string's escaping.

**Comment by axelhzf** [comment]
It is working now. Thanks for the PR

**Pull request merged**
